on:
  push:
    branches: [main]
  pull_request:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env
      - name: Install Rust nightly
        run: rustup toolchain install nightly
      - name: Set nightly as default
        run: rustup default nightly
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: weather-applet.flatpak
          manifest-path: one.weird.nandi.weather-applet.yml
          cache-key: flatpak-builder-${{ github.sha }}
